// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `oms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.oms.component;

public final class OmsServiceHolder extends Ice.ObjectHolderBase<OmsService>
{
    public
    OmsServiceHolder()
    {
    }

    public
    OmsServiceHolder(OmsService value)
    {
        this.value = value;
    }

    public void
    patch(Ice.Object v)
    {
        if(v == null || v instanceof OmsService)
        {
            value = (OmsService)v;
        }
        else
        {
            IceInternal.Ex.throwUOE(type(), v);
        }
    }

    public String
    type()
    {
        return _OmsServiceDisp.ice_staticId();
    }
}
