// **********************************************************************
//
// Copyright (c) 2003-2015 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.1
//
// <auto-generated>
//
// Generated from file `oms.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package com.lpmas.oms.component;

public interface OmsService extends Ice.Object,
                                    _OmsServiceOperations, _OmsServiceOperationsNC
{
    public static final String ice_staticId = "::com::lpmas::oms::component::OmsService";

    public static final long serialVersionUID = 1384803245L;
}
